version: 2

jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout
      - run:
          name: Install yarn
          command: npm install -g yarn
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Build statif files
          command: yarn build
