version: 2

jobs:
  build:
    docker:
      - image: node:9.2-alpine

    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn

      - run:
          name: Build statif files
          command: make build

      - run:
          name: Upload static files
          command: make s3-upload
